spring:
  profile.active: dev
  datasource:
    url: jdbc:mysql://localhost/forohub
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
api:
  security:
    secret: ${JWT_SECRET:123456}

